### ISSUE TITLE
add ast.isFunction() method

### ISSUE THREAD

**Issue by kevinb7** [estools/esutils#10]
proposed implementation:
```
ast.isFunction = function(node) {
    return node.type === "FunctionExpression" || node.type === "FunctionDeclaration";
};
```

**Comment by michaelficarra** [comment]
This doesn't seem very useful. Also, will arrows or concise methods be considered functions? I think that should be decided for each individual use case. :-1:.

**Comment by kevinb7** [comment]
Good point about the arrow functions... I'm working on some static analysis tools and I wanted to get a list of all named functions in a program.  What I'm looking for are functions that draw things so that I can do queries like "how do I draw a blah?" on a set of programs and return those that have a function called "blah" (that contains drawing functions like "line", "rect", "ellipse", etc.)  I also want to detect code smells where people are defining a function inside of the "draw" loop function.  I guess what I really wanted was a ```isNamedFunction``` method which is a little more involved and looks something like this:
```
as.isNamedFunction = function(node) {
   if (node.type === "FunctionExpression" && parent.type === "AssignmentExpression") {
       return true;
   } else if (node.type === "FunctionDeclaration" && parent.type === "Declarator") {
       return true;
   }
}
```
The funny thing is that if you want to retrieve the function name then you need pretty much the same logic anyway's so having one function for determining if a node is a named function and one for getting the node name is kind of redundant.

**Comment by michaelficarra** [comment]
```js
function getFunctionName(node) {
  if (/Function/.test(node.type) && node.id != null)
    return node.id.name;
}
```

**Comment by kevinb7** [comment]
I ended up using:
```
var getFunctionName = function(node, parent) {
    if (node.type === "FunctionExpression") {
        if (parent.type === "VariableDeclarator") {
            return parent.id.name;
        } else if (parent.type === "AssignmentExpression") {
            return parent.left.name;
        }
    }
};
```
So that it will handle things like ```var foo = function() { ... }``` and output ```foo``` as the name of the function.
