### ISSUE TITLE
esutils.code.isIdentifierPart doesn't recognise ES6 IdentifierParts

### ISSUE THREAD

**Issue by michaelficarra** [estools/esutils#11]
The only one I'm aware of is `\u{e01d5}`. /cc @mathiasbynens I think we just need to remove these lines from generate-identifier-regex.js:

```js
        .removeRange(0x010000, 0x10FFFF) // remove astral symbols
```

**Comment by mathiasbynens** [comment]
We should use `ID_Start` and `ID_Continue` if we want to implement ES6 semantics properly, although the end result is more or less the same as with your proposal ([U+2E2F aside](https://mathiasbynens.be/notes/javascript-identifiers-es6#acceptable-unicode-symbols)).

See <https://gist.github.com/mathiasbynens/6334847#file-javascript-identifier-regex-js>.

**Comment by mathiasbynens** [comment]
I’ve submitted a PR that updates the regular expressions. Left to do:

- [ ] Fix `isIdentifierStart` and `isIdentifierPart` so they consume astral symbols (i.e. surrogate pairs) as a whole

Any takers?
