### ISSUE TITLE
Add isKeyword(word, dialect, strict) method

### ISSUE THREAD

**Issue by zxqfox** [estools/esutils#18]
Is it possible to make resolver and combine `isKeyword*` methods to one with dialect keyword?

For now we have this: https://github.com/zxqfox/node-jscs/blob/issues/824/lib/reserved-words.js

**Comment by michaelficarra** [comment]
No, I don't like this. Especially since strict doesn't even apply for ES3. It's just as easy to choose the function you call as it is to choose the dialect value you pass to this function.
