### ISSUE TITLE
Support ast.isES5Constructor?

### ISSUE THREAD

**Issue by kevinoid** [estools/esutils#22]
In the discussion for eslint/eslint#6085, @nzakas raised the idea that [`isES5Constructor`](https://github.com/eslint/eslint/blob/v2.9.0/lib/ast-utils.js#L57) might be a good fit for `esutils`.  What do you think?  Would a function for recognizing ES5 constructor functions, similar to [`isES5Constructor`](https://github.com/eslint/eslint/blob/v2.9.0/lib/ast-utils.js#L57), be appropriate for inclusion in `esutils`?  If so, I can send a PR to work out specifics.

As part of a broader question, are convention-based and/or heuristic functions appropriate for `esutils`, or is the scope of the project limited to objective/specified criteria?

Thanks for considering,
Kevin

**Comment by michaelficarra** [comment]
I feel strongly that this function is not appropriate for esutils. If there was an official ECMAScript notion of a "constructor identifier", then it would fit, but this is a concept that simply does not exist in ECMAScript.

**Comment by nzakas** [comment]
Sorry, I totally misunderstood the code I was looking at. For whatever reason, I thought `isES5Constructor` was coming from this  package. Since it's not, we can take care of it in ESLint. Sorry for the confusion!
